CREATE DATABASE BookStore
GO

USE BookStore
GO

CREATE TABLE CategoryGroup
(
	GroupID VARCHAR(10) NOT NULL,
	GroupName NVARCHAR(100) NOT NULL,

	PRIMARY KEY(GroupID)
)
GO

CREATE TABLE Category
(
	CategoryID VARCHAR(10) NOT NULL,
	CategoryName NVARCHAR(100) NOT NULL,
	CategoryDescription TEXT NULL,
	Url VARCHAR(50) NOT NULL,

	CateGroupID VARCHAR(10) NOT NULL,

	PRIMARY KEY(CategoryID),
	FOREIGN KEY(CateGroupID) REFERENCES CategoryGroup(GroupID) ON DELETE CASCADE
)
GO

CREATE TABLE Producer
(
	ProducerID VARCHAR(10) NOT NULL,
	ProducerName NVARCHAR(100) NOT NULL,
	ProducerAddress NVARCHAR(200) NULL,
	PhoneNumber VARCHAR(20) NULL,
	FAX VARCHAR(20) NULL,
	Email VARCHAR(100) NULL,
	Website VARCHAR(100) NULL,
	Url VARCHAR(50) NOT NULL,

	PRIMARY KEY(ProducerID)
)
GO

CREATE TABLE Author 
(
	AuthorID VARCHAR(10) NOT NULL,
	AuthorName NVARCHAR(100) NOT NULL,
	PhoneNumber VARCHAR(20) NULL,
	Url VARCHAR(50) NOT NULL,

	PRIMARY KEY(AuthorID)
)
GO

CREATE TABLE Book 
(
	BookID VARCHAR(10) NOT NULL,
	BookName NVARCHAR(200) NOT NULL,
	Price INT NOT NULL,
	DiscountPercent INT NOT NULL,
	Quantity INT NOT NULL,
	TotalSell INT NOT NULL,
	Avatar VARCHAR(50),
	CreateByDate DATE DEFAULT GETDATE(),
	Url VARCHAR(50) NOT NULL,

	Publisher NVARCHAR(100) NULL,
	PublicByDate DATE NULL,
	BookCover NVARCHAR(50) NULL,
	Pages INT NULL,
	BookDescription TEXT NULL,

	AuthorID VARCHAR(10) NOT NULL,
	ProducerID VARCHAR(10) NOT NULL,

	PRIMARY KEY(BookID),
	FOREIGN KEY(AuthorID) REFERENCES Author(AuthorID) ON DELETE CASCADE,
	FOREIGN KEY(ProducerID) REFERENCES Producer(ProducerID) ON DELETE CASCADE
)
GO

CREATE TABLE Book_Category
(
	CategoryID VARCHAR(10) NOT NULL,
	BookID VARCHAR(10) NOT NULL,

	PRIMARY KEY(CategoryID, BookID),
	FOREIGN KEY(CategoryID) REFERENCES Category(CategoryID) ON DELETE CASCADE,
	FOREIGN KEY(BookID) REFERENCES Book(BookID) ON DELETE CASCADE
)
GO

CREATE TABLE News
(
	NewsID VARCHAR(10) NOT NULL,
	NewsName NVARCHAR(200) NOT NULL,
	Content NTEXT NULL,
	PostByDate DATE DEFAULT GETDATE(),

	PRIMARY KEY(NewsID)
)

CREATE TABLE [Role]
(
	RoleID VARCHAR(10) NOT NULL,
	RoleName NVARCHAR(50) NOT NULL,

	PRIMARY KEY(RoleID)
)

CREATE TABLE [User]
(
	UserID VARCHAR(10) NOT NULL,
	UserName VARCHAR(28) NOT NULL,
	[Password] VARCHAR(28) NOT NULL,
	CreatedByDate DATE DEFAULT GETDATE(),

	RoleID VARCHAR(10) NOT NULL,

	PRIMARY KEY(UserID),
	FOREIGN KEY(RoleID) REFERENCES [Role](RoleID) ON DELETE CASCADE
)

CREATE TABLE Customer
(
	CustomerID VARCHAR(10) NOT NULL,
	CustomerAddress NVARCHAR(200) NOT NULL,
	CustomerName NVARCHAR(100) NULL,
	Gender BIT NULL,
	Birth DATE NULL,
	PhoneNumber VARCHAR(20) NULL,
	Email VARCHAR(100) NULL,

	UserID VARCHAR(10) NOT NULL,

	PRIMARY KEY(CustomerID),
	FOREIGN KEY(UserID) REFERENCES [User](UserID) ON DELETE CASCADE
)
GO

CREATE TABLE Wishlist
(
	CustomerID VARCHAR(10) NOT NULL,
	BookID VARCHAR(10) NOT NULL,

	PRIMARY KEY(CustomerID, BookID),
	FOREIGN KEY(CustomerID) REFERENCES Customer(CustomerID) ON DELETE CASCADE,
	FOREIGN KEY(BookID) REFERENCES Book(BookID) ON DELETE CASCADE
)
GO


CREATE TABLE Payment
(
	PaymentID VARCHAR(10) NOT NULL,
	PaymentName NVARCHAR(100) NOT NULL,

	PRIMARY KEY(PaymentID)
)
GO

CREATE TABLE [Order]
(
	OrderID VARCHAR(10) NOT NULL,
	[Address] NVARCHAR(200) NULL,
	OrderByDate [date] DEFAULT GETDATE(),
	[Status] [nvarchar](50) DEFAULT 'Giỏ hàng',
	Notes TEXT NULL,
	Total INT NOT NULL,
	
	CustomerID VARCHAR(10) NOT NULL,
	PaymentID VARCHAR(10) NOT NULL,

	PRIMARY KEY(OrderID),
	FOREIGN KEY(CustomerID) REFERENCES Customer(CustomerID) ON DELETE CASCADE,
	FOREIGN KEY(PaymentID) REFERENCES Payment(PaymentID) ON DELETE CASCADE
)
GO

CREATE TABLE OrderDetail
(
	Quantity INT NOT NULL,
	Price INT NOT NULL,
	
	OrderID VARCHAR(10) NOT NULL,
	BookID VARCHAR(10) NOT NULL,

	PRIMARY KEY(OrderID, BookID),
	FOREIGN KEY(OrderID) REFERENCES [Order](OrderID) ON DELETE CASCADE,
	FOREIGN KEY(BookID) REFERENCES Book(BookID) ON DELETE CASCADE
)
GO

CREATE TABLE Review
(
	ReviewID VARCHAR(10) NOT NULL,
	ReviewByDate DATE DEFAULT GETDATE(),
	Content NTEXT NULL,
	
	BookID VARCHAR(10) NOT NULL,
	CustomerID VARCHAR(10) NOT NULL,

	PRIMARY KEY(ReviewID),
	FOREIGN KEY(BookID) REFERENCES Book(BookID) ON DELETE CASCADE,
	FOREIGN KEY(CustomerID) REFERENCES Customer(CustomerID) ON DELETE CASCADE
)
GO